name: Build and deploy
on:
  push:
    branches: [main]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          registry: registry.dockerdeploy.cloud
          username: qodcype0aw
          password: ${{ secrets.DOCKER_DEPLOY_KEY }}

      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          platforms: linux/arm64
          push: true
          tags: registry.dockerdeploy.cloud/qodcype0aw/web3-wallet-functions
          secrets: |
            "zerion_api_key=${{ secrets.ZERION_API_KEY }}"

      - name: Re-deploy
        run: |
          curl -XPUT -f -H 'Authorization: PAT ${{ secrets.DOCKER_DEPLOY_TOKEN }}' \
          'https://api.dockerdeploy.cloud/api/deployments/8s3ewP7o8W/deploy'
